### ISSUE TITLE
After running the data augmentation notebook, i find that the sketch-photo pairs are mismatched. For the same 1102 label, the sketch and photo are of different people. 

### ISSUE THREAD

**Issue by ramgj28** [Malikanhar/Sketch-to-Image#27]

**Comment by ramgj28** [comment]
It was a silly mistake on my part, the images had different sorting schemes in the file. So i made it the same. Issue resolved.

**Comment by ramgj28** [comment]
issue still exists

**Comment by ramgj28** [comment]
So i found that in the code snippet 
`p_filenames = glob.glob('Dataset/CUHK/Training photo/*')`  
` s_filenames = glob.glob('Dataset/CUHK/Training sketch/*')`

the order of the files need not be sorted. adding the sorted() function solved the issue for me.
`p_filenames = sorted(glob.glob('Dataset/CUHK/Training photo/*'))`
  `s_filenames = sorted(glob.glob('Dataset/CUHK/Training sketch/*'))`

Hope this helps someone. Cheers

**Comment by ASHU200210** [comment]
@ramgj28 Have you trained the model, If yes can you send it?
